### PR TITLE
Fix package name

### LINKED ISSUE #220: HACS Has faulty download url for release 2.3.1
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

A download of version 2.3.1 via HACS does not seem to be possible for me. For some reason the download url is wrong. The release zip file is called `average.zip`. HACS tries to download `https://github.com/Limych/ha-average/releases/download/tags/2.3.1/average_sensor.zip`

```
2024-01-22 21:55:50.272 ERROR (MainThread) [custom_components.hacs] <Integration Limych/ha-average> Failed to download https://github.com/Limych/ha-average/releases/download/tags/2.3.1/average_sensor.zip
2024-01-22 21:55:50.273 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139846613747136] Error handling message: Unknown error (unknown_error) <username> from <ip> (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/config/custom_components/hacs/websocket/repository.py", line 234, in hacs_repository_download
    await repository.async_install()
  File "/config/custom_components/hacs/repositories/base.py", line 893, in async_install
    await self.async_install_repository(version=version)
  File "/config/custom_components/hacs/repositories/base.py", line 990, in async_install_repository
    raise HacsException("Could not download, see log for details")
custom_components.hacs.exceptions.HacsException: Could not download, see log for details
```

### Describe the solution you'd like

I would like to have access to the most recent release via HACS.

### Describe alternatives you've considered

An alternative would be to download the sources directly and install the version manually. In order to make sure to get the next update I would prefer installing via HACS. What did work was the download of Version `2.3.0`.

### Additional context

Core:  2024.1.5
Supervisor: 2023.12.1
Operating System: 11.4
Frontend: 20240104.0

### PR DESCRIPTION
**Pull request by tompipe**
## Proposed change

Rename zip package to be downloaded by HACS

## Type of change

- [ ] Dependency upgrade
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (which adds functionality to an this integration)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #220 

## Checklist

- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Black (`black --fast custom_components`)

### CODE REVIEW

**Review by Argentumbolo — APPROVED** [review]

**Review by junado — APPROVED** [review]

**Review by Norrodar — APPROVED** [review]

**Review by SebastiaanKloos — APPROVED** [review]

**Review by aviadlevy — APPROVED** [review]

**Comment by aviadlevy** [comment]
waiting (im)patiently for this to get merged :)

**Review by AndrewDisco — APPROVED** [review]

**Review by IIAIronWolf — APPROVED** [review]

**Review by iRonin — APPROVED** [review]

**Review by k-szabi — APPROVED** [review]
Seems fine for me.

**Comment by SVH-Powel** [comment]
As this important PR has been here for 1 month without anyone approving it, tells me to perhaps stay away from this integration. The inbuilt statistics sensor in HA has some serious limitations that this one solves, but I try to stay away from code that is not maintained.

**Comment by Limych** [comment]
Thanks :heart:

**Pull request merged**
